version: '3.2'

services:
  ph:
    image: bitnami/phabricator:latest
#    restart: always
    expose:
      - 22
      - 80
      - 443
    ports:
      - 1022:22
      - 80:80
      - 443:443
    networks:
      - phabinet
    volumes:
      - type: bind
        source: ./phabricator/data
        target: /bitnami
    environment:
      - PHABRICATOR_HOST=<DNS NAME>
#      - PHABRICATOR_USERNAME=phabricator
#      - PHABRICATOR_PASSWORD=phabricator
#      - MARIADB_HOST=ph-db
      - PHP_MEMORY_LIMIT= 512M
    depends_on:
      - mariadb

  mariadb:
    image: bitnami/mariadb:latest
 #   ports:
 #     - 3306:3306
    networks:
      - phabinet
 #   restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--local-infile=0 --max_allowed_packet=33554432 --innodb-buffer-pool-size=1600M --sql_mode=STRICT_ALL_TABLES
#      - BITNAMI_DEBUG=true
    volumes:
      - type: bind
        source: ./phabricator/db
        target: /bitnami

networks:
  phabinet:
    driver: bridge

volumes:
  phabricator:
